### ISSUE TITLE
Jackson marshalling error

### ISSUE THREAD

**Issue by jrask** [sonyxperiadev/lumber-mill#30]
Dependency issue with jackson with the current version of aws-java-sdk.

    docker run --rm -e streamName=my_stream-v ~/.aws:/root/.aws lifelog/lumber-mill kcl.groovy

SEVERE: Caught exception while sync'ing Kinesis shards and leases
com.amazonaws.AmazonClientException: Unable to marshall request to JSON: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
	at com.amazonaws.services.kinesis.model.transform.DescribeStreamRequestMarshaller.marshall(DescribeStreamRequestMarshaller.java:96)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.describeStream(AmazonKinesisClient.java:673)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getStreamInfo(KinesisProxy.java:176)
	at com.amazonaws.services.kinesis.clientlibrary.proxies.KinesisProxy.getShardList(KinesisProxy.java:230)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.getShardList(ShardSyncer.java:288)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.syncShardLeases(ShardSyncer.java:112)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncer.checkAndCreateLeasesForNewShards(ShardSyncer.java:88)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.ShardSyncTask.call(ShardSyncTask.java:68)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.MetricsCollectingTaskDecorator.call(MetricsCollectingTaskDecorator.java:49)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.initialize(Worker.java:427)
	at com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker.run(Worker.java:356)
	at lumbermill.aws.kcl.internal.KinesisConsumerBootstrap.start(KinesisConsumerBootstrap.java:85)
	at lumbermill.aws.kcl.KCL.handleRecordBatch(KCL.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap.invoke(PojoMetaMethodSite.java:213)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at Script1.run(Script1.groovy:19)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:591)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:629)
	at groovy.lang.GroovyShell.evaluate(GroovyShell.java:600)
	at lumbermill.boot.ScriptBootstrap.loadFromScriptAsString(ScriptBootstrap.java:88)
	at lumbermill.boot.ScriptBootstrap.loadFromScriptAsFile(ScriptBootstrap.java:65)
	at lumbermill.boot.ScriptBootstrap.main(ScriptBootstrap.java:54)
Caused by: java.lang.NoSuchMethodError: com.fasterxml.jackson.dataformat.cbor.CBORGenerator.getOutputContext()Lcom/fasterxml/jackson/core/json/JsonWriteContext;
	at com.fasterxml.jackson.dataformat.cbor.CBORGenerator.close(CBORGenerator.java:903)
	at com.amazonaws.protocol.json.SdkJsonGenerator.close(SdkJsonGenerator.java:239)

@somcsel

**Comment by jrask** [comment]
Merged
